# project information
site_name: "STR-25-001 Brew Widget"
site_author: "Stephen Eaton"
site_description: "ESP32 Based Tilt Hydrometer"

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - header.autohide

# Page Tree
nav:
  - Home: index.md
  - Checklists:
      - KiCAD:
          - Schematic: checklists/kicad_schematic.md
          - PCB: checklists/kicad_pcb.md
          - Manufacturing - JLPCB: checklists/kicad_jlpcb.md
      - Github:
          - Release: checklists/github_release.md
  - Hardware:
      - Overview: hardware/overview.md
      - Mechanical: hardware/mechanical.md
      - License: license.md
  - Firmware:
      - Overview: firmware/overview.md
      - License: license.md
  - Bill of Materials:
      - bom.md
  - Design:
      - design/design.md
  - GitHub: github.md
  - Authors: authors.md
  - Change Log: changelog.md
  - References: references.md

# Repository
repo_name: "madeinoz67/STR-25-001-Brew-Widget"
repo_url: https://github.com/madeinoz67/STR-25-001-Brew-Widget
edit_uri: ""

# plugins
plugins:
  - search
  - mermaid2
  - autorefs

extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js

# extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # Copyright

copyright: Copyright &copy; 2025 Stephen Eaton

# footer customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/madeinoz67/brew-widget
# Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
# - auto
